import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { UiContextProvider } from "@/context/ui-context";
import BaseContextProvider from "@/context/base-context";
import { QueryContextProvider } from "@/context/query-context";

const geistSans = Plus_Jakarta_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  antialiased`}>
        <QueryContextProvider>
          <UiContextProvider>
            <BaseContextProvider>{children}</BaseContextProvider>
          </UiContextProvider>
        </QueryContextProvider>
      </body>
    </html>
  );
}
